### PR TITLE
Create account bdd tests

### LINKED ISSUE #89: US 2-4 Test Create a Account

### PR DESCRIPTION
**Pull request by TheJoeship**
Added tests and Mock object for CreateAccountUI

### CODE REVIEW

**Review by HaikunBarryZhu — APPROVED** [review]
Looks good

**Review by ZiwenLiu35 — APPROVED** [review]
good works

**Comment by jierubai** [comment]
Looks good to me

**Review by jierubai — APPROVED** [review]

**Review by vincentsgherzi — APPROVED** [review]
good

**Review by AlbertL1 — APPROVED** [review]
Looks good

**Pull request merged**
