### PR TITLE
Barry's send email + BDDTest

### LINKED ISSUE #113: US10 - Email Setup
As a user, I want to be able to set up my email in SayIt Assistant 2, so that I can send emails to my friends using voice commands.

### LINKED ISSUE #121: US15 - Login

### LINKED ISSUE #122: Test Login/Auto login

### LINKED ISSUE #124: Test Email Setup

### PR DESCRIPTION
**Pull request by TheJoeship**

### CODE REVIEW

**Review by HaikunBarryZhu — APPROVED** [review]
Looks good

**Comment by jierubai** [comment]
Looks good

**Review by jierubai — APPROVED** [review]

**Review by jierubai — APPROVED** [review]

**Review by vincentsgherzi — APPROVED** [review]
Good

**Review by AlbertL1 — APPROVED** [review]
Looks good

**Review by ZiwenLiu35 — APPROVED** [review]
looks good

**Pull request merged**
