### PR TITLE
Added BDD tests for Creating Email

### LINKED ISSUE #81: US12 - Creating Email with Voice Command
As a user, I want to create an email using voice commands in SayIt Assistant 2, so that I can compose messages without typing.

### LINKED ISSUE #125: Test Create Email

### PR DESCRIPTION
**Pull request by HaikunBarryZhu**

### CODE REVIEW

**Review by ZiwenLiu35 — APPROVED** [review]
Looks good

**Review by jierubai — APPROVED** [review]
Looks good

**Review by vincentsgherzi — APPROVED** [review]
good

**Review by TheJoeship — APPROVED** [review]
Good!

**Review by ZiwenLiu35 — APPROVED** [review]

**Review by AlbertL1 — APPROVED** [review]
Looks good

**Pull request merged**
