### PR TITLE
Fix unit test bug

### LINKED ISSUE #57: Delete Bug
Main Screen disappear when click any delete button

### LINKED ISSUE #58: Clear all bug
Prompt History Title is cleared after clearAll

### LINKED ISSUE #60: Unit Test for Delete and clear All

### LINKED ISSUE #62: Unit Test for Prompt History

### PR DESCRIPTION
**Pull request by jierubai**

### CODE REVIEW

**Comment by jierubai** [comment]
Fix Unite Test Bugs

**Review by vincentsgherzi — APPROVED** [review]

**Review by ZiwenLiu35 — APPROVED** [review]

**Review by HaikunBarryZhu — APPROVED** [review]
All tests passed.

**Comment by ZiwenLiu35** [comment]
Code looks good and all tests passed

**Review by AlbertL1 — APPROVED** [review]
Looks good to me.

**Comment by TheJoeship** [comment]
All looks in order

**Review by TheJoeship — APPROVED** [review]

**Pull request merged**
