### PR TITLE
Voice command test

### LINKED ISSUE #71: US2 - Account Creation and Accessibility
As a user, I want to create an account with SayIt Assistant 2, so that I can access my research prompts and settings across multiple devices.

### LINKED ISSUE #72: US3 - Password Verification during Account Creation
As a user, I want SayIt Assistant 2 to verify my password during the account creation process, so that I can ensure it is entered correctly.

### LINKED ISSUE #74: US5 - Voice Command Questioning
As a user, I want to be able to ask questions using voice commands in SayIt Assistant 2, so that I can interact with the application hands-free.

### LINKED ISSUE #76: US7 - Deleting Prompts from Prompt History
As a user, I want the ability to delete specific prompts from the prompt history in SayIt Assistant 2, using voice commands or appropriate interface elements, so that I can remove unwanted or outdated questions.

### LINKED ISSUE #78: US9 - Clearing Entire Prompt History

### PR DESCRIPTION
**Pull request by jierubai**
processing voice commands with bdd story tests

### CODE REVIEW

**Review by HaikunBarryZhu — APPROVED** [review]
Good works

**Review by vincentsgherzi — APPROVED** [review]
looks good

**Review by ZiwenLiu35 — APPROVED** [review]
looks good

**Review by AlbertL1 — APPROVED** [review]
Looks good

**Review by TheJoeship — APPROVED** [review]

**Pull request merged**
