### PR TITLE
Bdd test

### LINKED ISSUE #59: BDD Test for Prompt History

### LINKED ISSUE #61: BDD Test for delete and clear all

### PR DESCRIPTION
**Pull request by jierubai**
Create BDD Tests for User Stories

### CODE REVIEW

**Review by ZiwenLiu35 — APPROVED** [review]
good tests, thank you

**Review by vincentsgherzi — APPROVED** [review]
trusting you!

**Review by HaikunBarryZhu — APPROVED** [review]

**Review by AlbertL1 — APPROVED** [review]
Looks good, thank you!

**Review by TheJoeship — APPROVED** [review]
Looks good!

**Pull request merged**
